name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.amd64
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/s2i-nginx:latest
      
      - name: Install S2I
        run: |
          curl -sSL https://github.com/openshift/source-to-image/releases/download/v1.3.1/source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz | tar xvz -C /tmp
          sudo mv /tmp/s2i /usr/local/bin
      
      - name: Build and push S2I image
        run: |
          s2i build ./dist ghcr.io/${{ github.repository_owner }}/s2i-nginx:latest ghcr.io/${{ github.repository_owner }}/lp-idphotobook:latest
          docker push ghcr.io/${{ github.repository_owner }}/lp-idphotobook:latest